[package]
name = "journald-writer"
version = "0.1.0"
authors = ["The journald-writer Authors <oss@nyantec.com>"]
edition = "2018"
license = "MirOS"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
nix = "0.22.0"
log = "0.4"
env_logger = "0.8"
chrono = "0.4"
serde_yaml = "0.8"
serde = { version = "1.0", features = [ "derive" ] }
getopts = "0.2"

log-writer = { version = "0.3", features = [ "serde" ] }
journald = { path = "../rust-journald" }
#journald = { git = "https://github.com/nyantec/rust-journald", rev = "81ba0b72b563406ce939f1f00b6467aa77cf1f6b" }
